name: Continuous Integration

on:
  push:
    branches-ignore:
      - main
      - dependabot/**
  pull_request:
    branches:
      - main

jobs:
  build-non-vsix:

    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build all projects (except VSIX)
        run: dotnet build Vinyl.slnf
      - name: Run Tests
        run: dotnet test Vinyl.slnf

  build-vsix:

    runs-on: windows-2022
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Restore packages
        run: dotnet restore
      - name: Build VSIX project
        run: msbuild src/Vinyl.Vsix/Vinyl.Vsix.csproj /v:m
