name: Continuous Integration

on: [push, pull_request]

jobs:
  run-tests:

    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
      - name: Run Tests
        run: dotnet test
      - name: Build Package
        run: dotnet build src/Vinyl.Package