name: Continuous Integration

on: [push, pull_request]

jobs:
  test-all:

    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Restore dotnet-format tool
        uses: xt0rted/dotnet-tool-restore@v1

      - name: Build all projects (except VSIX)
        run: dotnet build Vinyl.slnf

      - name: Run Tests
        run: dotnet test

      - name: Check for formatting issues
        uses: xt0rted/dotnet-format@v1
        with:
          only-changed-files: "true"