name: Continuous Integration

on: [push, pull_request]

jobs:
  test-all:

    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
      - name: Build all projects (except VSIX)
        run: dotnet build Vinyl.slnf
      - name: Run Tests
        run: dotnet test