name: Update lockfiles
on:
  workflow_dispatch:

jobs:
  lockfiles:
    runs-on: windows-2022
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # This cannot be the standard GITHUB_TOKEN, otherwise the CI build doesn't get kicked off by GitHub [1].
          # [1] https://github.com/marketplace/actions/git-auto-commit#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ secrets.PAT_REPO_FULL }}

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore --force-evaluate

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update lockfiles